# Generated by Django 4.1.3 on 2022-11-25 13:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
