# Generated by Django 4.1.4 on 2022-12-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Body',
            new_name='body',
        ),
    ]
