# Generated by Django 4.2 on 2023-04-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
